project:
  type: book
book:
  title: "CASA0023 Learnning Diary"
  author: "Arthur Zhang"
  date: "2026/2/19"
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2.qmd
    - week3_corrections.qmd
    - references.qmd
bibliography: references.bib
format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
editor: visual